### ISSUE TITLE
'Object.assign' should be overriden

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1208]
```js
Error: Cannot call method 'replace' of undefined
at Function.t._error (http://localhost:1351/hammerhead.js:2:4245)
at value (http://localhost:1351/hammerhead.js:2:4719)
at b (http://localhost:1351/r1TwR_TNW!s!utf-8/http://config1.veinteractive.com/scripts/5.0/capture-apps-5.0.0.js:7:15233)
at t._onWindowMessage (http://localhost:1351/hammerhead.js:4:7689)
at r (http://localhost:1351/hammerhead.js:8:26811)
at o (http://localhost:1351/hammerhead.js:4:8738)
at http://localhost:1351/hammerhead.js:3:31718
```

Sites:
http://lingualeo.ru/
http://www.samsung.com/uk/home

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Script to reproduce
```js
var iframe = document.createElement('iframe');

Object.assign(iframe, { src: '<url>'});

iframe.src; // iframe src contains non-proxied value
```
