### ISSUE TITLE
Script error then Node.nextSibling is null

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1469]
https://testcafe-hhhm.devexpress.com/history?timestamp=1517511893149&siteUrl=http://histats.com/

```js


at Object.Z [as isShadowUIElement] (http://localhost:1351/hammerhead.js:9:2046)
at Object.get (http://localhost:1351/hammerhead.js:2:18465)
at value (http://localhost:1351/hammerhead.js:2:26958)
at Function.sibling (http://localhost:1351/24iC5LL5j!s!utf-8/http://cdn1.ffcdn.net/js1/jquery.172-jquery-ui.182.json.min_2012_07_02.js:4:33128)
at children (http://localhost:1351/24iC5LL5j!s!utf-8/http://cdn1.ffcdn.net/js1/jquery.172-jquery-ui.182.json.min_2012_07_02.js:4:32222)
at Function.map (http://localhost:1351/24iC5LL5j!s!utf-8/http://cdn1.ffcdn.net/js1/jquery.172-jquery-ui.182.json.min_2012_07_02.js:3:13819)
at init.children (http://localhost:1351/24iC5LL5j!s!utf-8/http://cdn1.ffcdn.net/js1/jquery.172-jquery-ui.182.json.min_2012_07_02.js:4:32430)
at new b (http://localhost:1351/24iC5LL5j!s!utf-8/http://cdn1.ffcdn.net/js1/jquery.slider.pack.js:11:254)
at HTMLDivElement. (http://localhost:1351/24iC5LL5j!s!utf-8/http://cdn1.ffcdn.net/js1/jquery.slider.pack.js:11:11946)
at Function.each (http://localhost:1351/24iC5LL5j!s!utf-8/http://cdn1.ffcdn.net/js1/jquery.172-jquery-ui.182.json.min_2012_07_02.js:3:12712)


```

**Comment by miherlosev** [comment]
I'm working on this
