### ISSUE TITLE
The 'srcset' attribute should be overriden

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#1497]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

**Comment by miherlosev** [comment]
Need to proxy the `image.srcset` and `source.srcset` attributes in the same way as `image.src`.

**Comment by helgenlechner** [comment]
Since we need srcsets to work for some new tests I'm writing, I'm trying to get this feature added, but I'm having trouble running the tests, even in the unmodified master.

When I run `gulp test-server` I get the following error after "Should send the https request through the proxy" passes:

```
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:456:14)
    at Socket.ondata (_stream_readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:548:15)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:129:14)
```

When I run `gulp test-client`, the script outputs `QUnit server listens on http://localhost:2000`, but then nothing further happens.

Does anyone have any pointers what I'm doing wrong? I'm using Node v14.15.1. and Gulp version 4.0.2.

**Comment by Farfurix** [comment]
@helgenlechner 

Hello,

> I'm trying to get this feature added, but I'm having trouble running the tests, even in the unmodified master.

I wasn't able to reproduce it. Could you please try to follow all [the First look steps](https://github.com/DevExpress/testcafe-hammerhead#first-look)?

> When I run gulp test-client, the script outputs QUnit server listens on http://localhost:2000, but then nothing further happens.

You should navigate to this URL in your browser and click the "Run all" link or click some specific test.
