### ISSUE TITLE
Tests lose connection, failing at testcafe-hammerhead module

### ISSUE THREAD

**Issue by cmmv91** [DevExpress/testcafe-hammerhead#1736]
Tests fail with "Error: write EPIPE" relative to the testcafe-hammerhead module.

Error: Error: write EPIPE
    at Domain.<anonymous> (.../node_modules/testcafe-hammerhead/lib/request-pipeline/connection-reset-guard.js:20:15)
    at Domain.emit (events.js:182:13)
    at Domain.EventEmitter.emit (domain.js:442:20)
    at Domain._errorHandler (domain.js:224:23)
    at Object.setUncaughtExceptionCaptureCallback (domain.js:140:29)
    at process._fatalException (internal/bootstrap/node.js:440:31)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! ...@0.0.1 test-chrome: `npx testcafe chrome src/tests/ --assertion-timeout 30000`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the ...@0.0.1 test-chrome script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2018-08-22T21_45_15_397Z-debug.log

Node:
v10.5.0

Testcafe:
0.21.1

npm
6.3.0

chrome:
68.0.3440.106 (Official Build) (64-bit)

OSX
10.13.6

Tests don't run on headless chrome either, same error happens.
Tests run perfectly on Firefox and headless Firefox, the issue only happens with chrome.

**Comment by miherlosev** [comment]
Hi @cmmv91 

We've already fixed this problem. The fix will be included in `testcafe@0.22.0`.
