### ISSUE TITLE
Getting errors when running tests about http

### ISSUE THREAD

**Issue by doronsever** [DevExpress/testcafe-hammerhead#1806]
Please help...
On each test we run, we get this error at the end:

>  Error in fixture.beforeEach hook -
      Unhandled promise rejection:

      Error [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
      at new ClientRequest (_http_client.js:131:11)
      at Object.request (http.js:38:10)
      at Domain.<anonymous> (/Users/dorons/dev/management/mgmt-console/node_modules/testcafe-hammerhead/lib/request-pipeline/destination-request/index.js:90:47)
      at Domain.run (domain.js:322:14)
      at exports.default (/Users/dorons/dev/management/mgmt-console/node_modules/testcafe-hammerhead/lib/request-pipeline/connection-reset-guard.js:6:27)
      at DestinationRequest._send (/Users/dorons/dev/management/mgmt-console/node_modules/testcafe-hammerhead/lib/request-pipeline/destination-request/index.js:82:44)
      at new DestinationRequest (/Users/dorons/dev/management/mgmt-console/node_modules/testcafe-hammerhead/lib/request-pipeline/destination-request/index.js:78:14)
      at sendRequest (/Users/dorons/dev/management/mgmt-console/node_modules/testcafe-hammerhead/lib/request-pipeline/index.js:375:79)
      at Object.sendDestinationRequest (/Users/dorons/dev/management/mgmt-console/node_modules/testcafe-hammerhead/lib/request-pipeline/index.js:133:20)
      at next (/Users/dorons/dev/management/mgmt-console/node_modules/testcafe-hammerhead/lib/request-pipeline/index.js:403:46)

At first, I thought it is related that my testcafe server was running over HTTP and even opened a ticket about it.

But now the testcafe server runs over https and I still get this error.
I checked everywhere and i'm not calling any http request during our tests.
Also, we run this on a real production server and when we are browsing it using regular browser we are not getting any http/https warnings that chrome usually shuots when doing such violation.
How can I debug it?

**Comment by doronsever** [comment]
@LavrovArtem, unfortunately, I cannot give you the URL.
The tests stop to fails when we use the `-u` parameter.
Can you help me understand how to debug it so we can fix this issue properly?

**Comment by LavrovArtem** [comment]
I've researched the causes of the `Error [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"` error. It occurred when nodejs sent a request through the 'http:' protocol to the 'https:' server. The `destination-request/index.js` file is in charge of sending requests from our proxy to the destination server.

You can debug your server by using the `playground` task.
You can find steps to run below:
https://github.com/DevExpress/testcafe-hammerhead#first-look

**Comment by miherlosev** [comment]
I will close the issue because no activity has been encountered for a long time.
Feel free to reopen the issue if the problem persists and you can provide an example to reproduce it.
