### ISSUE TITLE
SyntaxError: JSON.parse at XMLHttpRequest

### ISSUE THREAD

**Issue by aszegedi** [DevExpress/testcafe-hammerhead#1839]
Hi,

I've faced this issue with TestCafe 0.23.2, that is not present with TestCafe 0.22.0:
```✖ Previously created OpenStack cluster has been removed successfully

   1) Error on page "https://cloud-24-canary.eng.hortonworks.com/clusters":

      SyntaxError: JSON.parse
          at parse (http://10.200.51.193:1337/hammerhead.js:1:22280)
          at XMLHttpRequest.f (http://10.200.51.193:1337/hammerhead.js:9:24666)

      Browser: Chrome 70.0.3538 / Mac OS X 10.14.0
```
I get this issue after:
```
await t
        .expect(ClusterPage.getWidget(clusterName + '-os'))
        .eql(0, 'check cluster widget has been removed in 15 minutes', { timeout: 900000 });
```
```
    static getWidget(clusterName: string) {
        const isWidgetExists = Selector(PageHelper.elementWithDataQa(clusterName)).with({ visibilityCheck: true })
            .exists;

        if (isWidgetExists) {
            return Selector(PageHelper.elementWithAttribute('data-stack-name', clusterName)).with({
                visibilityCheck: true
            }).count;
        } else {
            return 0;
        }
    }
```

Google Chrome run options: 
`{"path":"/Applications/Google Chrome.app","cmd":"--disable-infobars --disable-session-crashed-bubble --no-first-run --new-window --enable-automation --enable-logging --v=1 --no-sandbox --disable-background-networking --disable-software-rasterizer --user-data-dir=\"browser-data/google-chrome\" --disable-web-security --disable-extensions --disable-default-apps --disable-notifications --disable-sync --disable-translate --disable-save-password-bubble --disable-session-crashed-bubble --hide-scrollbars --metrics-recording-only --mute-audio --no-first-run --safebrowsing-disable-auto-update --password-store=basic --ignore-certificate-errors --allow-insecure-localhost","macOpenCmdTemplate":"open -n -a \"{{{path}}}\" --args {{{pageUrl}}} {{{cmd}}}"}`
TestCafe run options: `{"speed":0.7,"selectorTimeout":80000,"assertionTimeout":120000,"pageLoadTimeout":60000,"skipUncaughtErrors":true}`

**Comment by LavrovArtem** [comment]
Could you please search for an `xhr` request with the `500` status code in the `Network` tab of the Chrome devtools and send me the response that contains an error message?

**Comment by aszegedi** [comment]
Hi Artem,

Unfortunately I was not able to reproduce this neither manually nor with Debug or DebugOnFail modes. This is strange.

Even stranger, Today this issue has occurred only few times out of several runs. So I cannot provide more details for this right now.

Cluster termination have been done successfully. However I got the error at assertion step. What is your opinion? Do you have any hint on this?

Anyway, I think we can close this issue, because of I cannot reproduce this constantly and provide debug details...

**Comment by LavrovArtem** [comment]
I think I found the cause of this issue. I will try to fix it and will notify you once the fix is ready.

**Comment by LavrovArtem** [comment]
The fix is published in `testcafe@0.23.3-alpha.2`.
