### ISSUE TITLE
Invalid calling object in IE 11

### ISSUE THREAD

**Issue by sophalch** [DevExpress/testcafe-hammerhead#1846]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Test failed with "Invalid calling object" in IE 11 only. Chrome, Edge, and Firefox are fine.

1) Error on page ".../6CF134EFF8788553F5A82C19A750B4DC.cache.html":

  Invalid calling object

  Browser: IE 11.0.0 / Windows 10.0.0

   > 33 |    .click(Selector('#search'))

     at click (C:\sp\tests\ic\tests\login.js:33:6)
     at test (C:\sp\tests\ic\tests\login.js:13:1)
     at markeredfn (C:\Users\sp\AppData\Roaming\npm\node_modules\testcafe\src\api\wrap-test-function.js:18:28)
     at <anonymous> (C:\Users\sp\AppData\Roaming\npm\node_modules\testcafe\src\api\wrap-test-function.js:8:5)
     at fn (C:\Users\sp\AppData\Roaming\npm\node_modules\testcafe\src\test-run\index.js:238:19)
     at TestRun._executeTestFn (C:\Users\sp\AppData\Roaming\npm\node_modules\testcafe\src\test-run\index.js:234:38)
     at _executeTestFn (C:\Users\sp\AppData\Roaming\npm\node_modules\testcafe\src\test-run\index.js:279:24)

### What is the expected behavior?
Expect test to pass

### Specify your

* operating system: Windows 10
* testcafe version: 0.22.0
* node.js version: 8.9.4

Since this is an internal site with login credential required, I'm not sure how you could replicate it.
This site is using multiple iframes, and when the search button is pressed, the issue appears as above.

Please let me know how I could debug it.

**Comment by guptaakhil** [comment]
I am facing same issue just curious to know how to incorporate this change in code.
