### ISSUE TITLE
Flaky test select elements: click triggers "Cannot read property 'parent' of undefined"

### ISSUE THREAD

**Issue by mweibel** [DevExpress/testcafe-hammerhead#1889]
### What is your Test Scenario?
Open a page with one to `n` `<select>` tags. We select the first select tag out of it and select a specific option. Then we click on that option.

```javascript
fixture`The failing test`
  .page`${baseURL}/SOMERELATIVEURL`

test('Has interactive variants', async t => {
  const variants = await testIdSelector('product-variants-select')
  const variant = variants.nth(0)

  const variantOptions = variant.find('option')
  await t.expect(variantOptions.count).eql(9)

  const optionToSelect = variantOptions.withText('140.0 cm')
  await t.expect(optionToSelect.exists).ok()

  const getPageUrl = ClientFunction(() => window.location.href.toString())

  await t.click(variant)
    .click(optionToSelect)
    .expect(getPageUrl()).contains(`${baseURL}/SOME_OTHER_RELATIVE_URL`, { timeout: 10000 })
})
```
 
### What is the Current behavior?
This specific test is quite flaky on the CI where we execute it in a docker container. The error we get in that case is always the same:
```

 The failing test
 ✖ Has interactive variants

   1) Error on page "http://localhost:3002/SOMERELATIVEURL":

      TypeError: Cannot read property 'parent' of undefined
          at b (http://172.17.0.3:33154/hammerhead.js:10:2044)
          at s (http://172.17.0.3:33154/hammerhead.js:1:26914)
          at Function.t._getCurrentInfoManager
      (http://172.17.0.3:33154/hammerhead.js:9:13976)
          at http://172.17.0.3:33154/hammerhead.js:9:14160
          at http://172.17.0.3:33154/hammerhead.js:3:21621
          at HTMLSelectElement.dispatchEvent
      (http://172.17.0.3:33154/hammerhead.js:3:15741)
          at e._raiseDispatchEvent
      (http://172.17.0.3:33154/hammerhead.js:4:17959)
          at e._dispatchEvent
      (http://172.17.0.3:33154/hammerhead.js:4:17650)
          at e.change (http://172.17.0.3:33154/hammerhead.js:4:20479)
          at B (http://172.17.0.3:33154/testcafe-ui.js:1:17061)

      Browser: HeadlessChrome 0.0.0 / Linux 0.0.0

          98 |  await t.expect(optionToSelect.exists).ok()
          99 |
         100 |  const getPageUrl = ClientFunction(() =>
      window.location.href.toString())
         101 |
         102 |  await t.click(variant)
       > 103 |    .click(optionToSelect)
         104 |
      .expect(getPageUrl()).contains(`${baseURL}/SOME_OTHER_RELATIVE_URL`, {
      timeout: 10000 })
         105 |})
         106 |
         107 |fixture`The failing test`
         108 |
      .page`${baseURL}/SOMERELATIVEURL`

         at click
      (/relative/path/to/test/productDetail/sometest.test.js:103:6)
```
Seldomly it fails on the local devs machines too, but that's quite seldom.  

### What is the Expected behavior?
It should work always or fail in some way that is predictable.
 
### Your Environment details:
 
* testcafe version:                   0.23.2
* node.js version:                    v10.12.0
* command-line arguments:  testcafe --app='npm run test:mock-api' 'chromium:headless' ./test
* browser name and version: Chromium
* platform and version:          Linux

**Comment by mweibel** [comment]
Thanks for your investigation, that helps!
Unfortunately at the moment I can't show you the page/code. It will be in about a month or so live and then I could show it to you. 
I'll close the issue for now and reopen in case that's then still an issue we have.

Thanks for the help!

**Comment by mweibel** [comment]
FYI moving the fixture to an own file seemed to have helped. Didn't have issues since then anymore.

**Comment by LavrovArtem** [comment]
We are happy to hear that you found the solution.
