### ISSUE TITLE
IE breaks with TypeError: Invalid calling object in _processChildren() and getFirstChild() 

### ISSUE THREAD

**Issue by hnordberg** [DevExpress/testcafe-hammerhead#2236]
### What is your Scenario?
Run test on IE on Windows 10.
 
### What is the Current behavior?
IE stops script with 'Invalid Calling Object' error.
 
### What is your public web site URL?
https://www.johnmuirhealth.com/doctor

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
import { Selector } from "testcafe";

fixture `Simple Test`;

test('simple test', async t => {
  await t.navigateTo('https://www.johnmuirhealth.com/doctor');
  await t.expect( Selector('.provider-name').exists ).ok();
}); 
```
</details>

<details>
<summary>Screenshots:</summary>

```
testcafe ie ./tests/simple.test.js
Using locally installed version of TestCafe.
 Running tests in:
 - Internet Explorer 11.0 / Windows 10
 Simple Test
 × simple test
   1) A JavaScript error occurred on "https://www.johnmuirhealth.com/doctor".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the
      "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      JavaScript error details:
      TypeError: Invalid calling object
         at r.getFirstChild (http://172.29.37.13:54112/hammerhead.js:12:28542)
         at getter (http://172.29.37.13:54112/hammerhead.js:12:10460)
         at sc.firstChild (https://www.johnmuirhealth.com/webcommon/lib/webcomponentsjs-2.1.3/webcomponents-bundle.js:127:24)
         at Bc.firstChild.get (https://www.johnmuirhealth.com/webcommon/lib/webcomponentsjs-2.1.3/webcomponents-bundle.js:133:226)
         at pe (https://www.johnmuirhealth.com/webcommon/lib/webcomponentsjs-2.1.3/webcomponents-bundle.js:190:405)
         at Q (https://www.johnmuirhealth.com/webcommon/lib/webcomponentsjs-2.1.3/webcomponents-bundle.js:192:98)
         at ve (https://www.johnmuirhealth.com/webcommon/lib/webcomponentsjs-2.1.3/webcomponents-bundle.js:196:253)
         at S (https://www.johnmuirhealth.com/webcommon/lib/webcomponentsjs-2.1.3/webcomponents-bundle.js:196:931)
         at Anonymous function (https://www.johnmuirhealth.com/webcommon/lib/webcomponentsjs-2.1.3/webcomponents-bundle.js:214:527)
         at Global code (https://www.johnmuirhealth.com/webcommon/lib/webcomponentsjs-2.1.3/webcomponents-bundle.js:11:2)
      Browser: Internet Explorer 11.0 / Windows 10

 1/1 failed (3s)
```
</details>

### Steps to Reproduce:

1. Put the code above into simple.test.js
2. Execute this command: testcafe ie simple.test.js
3. See the error (see detailed error output above): TypeError: Invalid calling object

Making these changes to hammerhead.js makes it work:

```js
_proto._processChildren = function _processChildren(el) {
    if (!el.querySelectorAll) return;
    //var children = (0, _querySelector.getNativeQuerySelectorAll)(el).call(el, '*');
    var children = el.querySelectorAll('*');
    //var length = _nativeMethods.default.nodeListLengthGetter.call(children);
    var length = children.length;
    for (var i = 0; i < length; i++) {
        this._processElement(children[i]);
    }
};
```
and
```js
_proto.getFirstChild = function getFirstChild(el) {
    //var length = _nativeMethods.default.nodeListLengthGetter.call(el.childNodes);
    var length = el.childNodes.length;
    var filteredNodes = this._filterNodeList(el.childNodes, length);
    return filteredNodes[0] || null;
};
```
 
### Your Environment details:

* node.js version:                    10.16.3
* browser name and version: IE 11
* platform and version:          Windows 10
* other:                                   TestCafe 1.8.1

**Comment by aleks-pro** [comment]
Hello @hnordberg ,

I have reproduced the issue. We will research it and update this thread as soon as we have any news.

**Comment by LavrovArtem** [comment]
For team:

`/webcommon/lib/webcomponentsjs-2.1.3/webcomponents-bundle.js`

The file above on the destination site contains the following code:
```js
parentNode:function(a){return I.parentNode.get.call(a)},
firstChild:function(a){return I.firstChild.get.call(a)},lastChild:function(a){return I.lastChild.get.call(a)},previousSibling:function(a){return I.previousSibling.get.call(a)},nextSibling:function(a){return I.nextSibling.get.call(a)},childNodes:function(a){return Array.prototype.slice.call(I.childNodes.get.call(a))},parentElement:function(a){return I.parentElement.get.call(a)},previousElementSibling:function(a){return I.previousElementSibling.get.call(a)},nextElementSibling:function(a){return I.nextElementSibling.get.call(a)},
innerHTML:function(a){return I.innerHTML.get.call(a)},textContent:function(a){return I.textContent.get.call(a)},children:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return qc.children.get.call(a);case Node.DOCUMENT_NODE:return rc.children.get.call(a);default:return I.children.get.call(a)}},firstElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return qc.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return rc.firstElementChild.get.call(a);default:return I.firstElementChild.get.call(a)}},
lastElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return qc.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return rc.lastElementChild.get.call(a);default:return I.lastElementChild.get.call(a)}}};var J=A.Ba?sc:F;function tc(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
```

So we need to use the native `childNodes` getter. Also, check other getters and setters that are overridden in this code. It seems this code is applied only in IE11 because I cannot reproduce the issue in Chrome.

**Comment by hnordberg** [comment]
>  It seems this code is applied only in IE11 because I cannot reproduce the issue in Chrome.

Yes, that file is the polyfill for Web Components and is not needed for Chrome (and other recent browsers).

**Comment by Farfurix** [comment]
@hnordberg 

Hello,

I found another issue related to your project: https://github.com/DevExpress/testcafe-hammerhead/issues/2330. You can track our progress there.
