### ISSUE TITLE
Test Frequently Lose Connected (EPIPE error)

### ISSUE THREAD

**Issue by qualityshepherd** [DevExpress/testcafe-hammerhead#2264]
I've been seeing this occasionally and now almost every time I run all my tests (~50) against our staging environment. After a _lot_ of debugging, I discovered the issue is with all recent versions of Testcafe and Node lts versions > 8.17.0. Same tests fail on v10 & v12. 

I've not been able to find _sharable_ test code that reproduces the problem _yet_. I'll update if I can... I see a similar issue has been reported previously (#1647). 

I'm running Testcafe 1.8.2; Chrome 80.0.3987.122; macOS 10.14.6 but I've also seen this issue (less frequently) from our Linux CI server. 

```
1 Uncaught exception:

  Error: write EPIPE
  at afterWriteDispatched (internal/stream_base_commons.js:154:25)
  at writeGeneric (internal/stream_base_commons.js:145:3)
  at Socket._writeGeneric (net.js:780:11)
  at Socket._write (net.js:792:8)
  at doWrite (_stream_writable.js:441:12)
  at writeOrBuffer (_stream_writable.js:425:5)
  at Socket.Writable.write (_stream_writable.js:316:11)
  at TLSSocket.ondata (_stream_readable.js:714:22)
  at TLSSocket.emit (events.js:311:20)
  at TLSSocket.EventEmitter.emit (domain.js:505:15)

  Browser: Chrome 80.0.3987.122 / macOS 10.14.6
```

**Comment by aleks-pro** [comment]
Hello @qualityshepherd ,

Thank you for reporting the issue. We are awaiting the test code example to be able to reproduce and research the issue on our side.

**Comment by qualityshepherd** [comment]
Yup... I'm trying to find one. It seems like it takes a good number of tests before it appears 🤷‍♂ I'll update this asap...

**Comment by rmkranack** [comment]
> I've been seeing this occasionally and now almost every time I run all my tests (~50) against our staging environment. After a _lot_ of debugging, I discovered the issue is with all recent versions of Testcafe and Node lts versions > 8.17.0. Same tests fail on v10 & v12.
> 
> I've not been able to find _sharable_ test code that reproduces the problem _yet_. I'll update if I can... I see a similar issue has been reported previously (#1647).
> 
> I'm running Testcafe 1.8.2; Chrome 80.0.3987.122; macOS 10.14.6 but I've also seen this issue (less frequently) from our Linux CI server.
> 
> ```
> 1 Uncaught exception:
> 
>   Error: write EPIPE
>   at afterWriteDispatched (internal/stream_base_commons.js:154:25)
>   at writeGeneric (internal/stream_base_commons.js:145:3)
>   at Socket._writeGeneric (net.js:780:11)
>   at Socket._write (net.js:792:8)
>   at doWrite (_stream_writable.js:441:12)
>   at writeOrBuffer (_stream_writable.js:425:5)
>   at Socket.Writable.write (_stream_writable.js:316:11)
>   at TLSSocket.ondata (_stream_readable.js:714:22)
>   at TLSSocket.emit (events.js:311:20)
>   at TLSSocket.EventEmitter.emit (domain.js:505:15)
> 
>   Browser: Chrome 80.0.3987.122 / macOS 10.14.6
> ```

Was there a resolution for this? I am getting a very similar error using TestCafe 1.13.0

   1) Uncaught exception:
      
      Error: write EPIPE
      at afterWriteDispatched (internal/stream_base_commons.js:156:25)
      at writeGeneric (internal/stream_base_commons.js:147:3)
      at Socket._writeGeneric (net.js:785:11)
      at Socket._write (net.js:797:8)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at Socket.Writable.write (internal/streams/writable.js:303:10)
      at TLSSocket.ondata (internal/streams/readable.js:719:22)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket.EventEmitter.emit (domain.js:529:15)
      at addChunk (internal/streams/readable.js:309:12)

      Browser: Chrome 89.0.4389.114 / macOS 10.15.7

**Comment by rmkranack** [comment]
> > I've been seeing this occasionally and now almost every time I run all my tests (~50) against our staging environment. After a _lot_ of debugging, I discovered the issue is with all recent versions of Testcafe and Node lts versions > 8.17.0. Same tests fail on v10 & v12.
> > I've not been able to find _sharable_ test code that reproduces the problem _yet_. I'll update if I can... I see a similar issue has been reported previously (#1647).
> > I'm running Testcafe 1.8.2; Chrome 80.0.3987.122; macOS 10.14.6 but I've also seen this issue (less frequently) from our Linux CI server.
> > ```
> > 1 Uncaught exception:
> > 
> >   Error: write EPIPE
> >   at afterWriteDispatched (internal/stream_base_commons.js:154:25)
> >   at writeGeneric (internal/stream_base_commons.js:145:3)
> >   at Socket._writeGeneric (net.js:780:11)
> >   at Socket._write (net.js:792:8)
> >   at doWrite (_stream_writable.js:441:12)
> >   at writeOrBuffer (_stream_writable.js:425:5)
> >   at Socket.Writable.write (_stream_writable.js:316:11)
> >   at TLSSocket.ondata (_stream_readable.js:714:22)
> >   at TLSSocket.emit (events.js:311:20)
> >   at TLSSocket.EventEmitter.emit (domain.js:505:15)
> > 
> >   Browser: Chrome 80.0.3987.122 / macOS 10.14.6
> > ```
> 
> Was there a resolution for this? I am getting a very similar error using TestCafe 1.13.0
> 
> 1. Uncaught exception:
>    Error: write EPIPE
>    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
>    at writeGeneric (internal/stream_base_commons.js:147:3)
>    at Socket._writeGeneric (net.js:785:11)
>    at Socket._write (net.js:797:8)
>    at writeOrBuffer (internal/streams/writable.js:358:12)
>    at Socket.Writable.write (internal/streams/writable.js:303:10)
>    at TLSSocket.ondata (internal/streams/readable.js:719:22)
>    at TLSSocket.emit (events.js:315:20)
>    at TLSSocket.EventEmitter.emit (domain.js:529:15)
>    at addChunk (internal/streams/readable.js:309:12)
>    Browser: Chrome 89.0.4389.114 / macOS 10.15.7

I noticed the issue does not occur on Firefox. It seems to fail on pages that have this message in the developer console "Autofocus processing was blocked because a document's URL has a fragment '#/info'."

**Comment by wentwrong** [comment]
@rmkranack, I tried to reproduce the issue on pages that have both the '#/info' fragment and the message in the developer console, but in my case everything works fine - seems that it's not the original cause. Could you please share a reproducible example (the code of the failed test which we can run and see the error)?
