### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by ssemrau** [DevExpress/testcafe-hammerhead#2317]
### What is your Scenario?
e2e test using ```createTestacafe``` and ```createRunner```
 
### What is the Current behavior?
Testcafe stops working and exception as follows is thrown
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at RequestPipelineContext.redirect (C:\MyTests\local_modules\testcafe-runner\node_modules\testcafe-hammerhead\lib\request-pipeline\context.js:278:9)
    at TestRun.handlePageError (C:\MyTests\local_modules\testcafe-runner\node_modules\testcafe\src\test-run\index.js:287:13)
    at SessionController.handlePageError (C:\MyTests\local_modules\testcafe-runner\node_modules\testcafe\src\test-run\session-controller.js:43:36)
    at error (C:\MyTests\local_modules\testcafe-runner\node_modules\testcafe-hammerhead\lib\request-pipeline\utils.js:81:48)
    at DestinationRequest.<anonymous> (C:\MyTests\local_modules\testcafe-runner\node_modules\testcafe-hammerhead\lib\request-pipeline\utils.js:62:9)
    at DestinationRequest.emit (events.js:209:13)
    at DestinationRequest.EventEmitter.emit (domain.js:476:20)
    at DestinationRequest._onError (C:\MyTests\local_modules\testcafe-runner\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:171:17)
    at ClientRequest.<anonymous> (C:\MyTests\local_modules\testcafe-runner\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:93:40) {
  domainThrown: true
}
npm ERR! code ELIFECYCLE
npm ERR! errno 7
```

### What is the Expected behavior?
TestCafe does not throw exception.
 
### What is your public web site URL?
Not available.

### Your Environment details:

* node.js version:                   12.10.0 
* browser name and version: Chrome 80.0.3987.116
* platform and version:          Windows 10
* Testcafe:                               1.8.4
* Testcafe-hammerhead:        16.2.3

### Important note
Testcafe-hammerhead 16.2.3 comes with Testcafe 1.8.4
When downgraded to excact verison of Testcafe 1.8.1 which pulls Testcafe-hammerhead 16.0.2 then all test suites works as expected and exception is not thrown.

**Comment by SergeyShurygin** [comment]
We are aware about a similar problem and our team is already working on it. Please wait for the next testcafe release and check if the issue persists.

**Comment by ssemrau** [comment]
@SergeyShurygin as you closed this one, is there any other reference bug/request/pull-request to track, so that I can see when expect issue to be solved?

**Comment by AlexSkorkin** [comment]
@ssemrau, we addressed a similar issue in the context of this PR:

[https://github.com/DevExpress/testcafe-hammerhead/pull/2315](https://github.com/DevExpress/testcafe-hammerhead/pull/2315)

It was merged and the fix will be available in our next official update. See if the next update addresses the issue you submitted, too.
