### ISSUE TITLE
TypeError: hammerhead.extend is not a function

### ISSUE THREAD

**Issue by djbreen7** [DevExpress/testcafe-hammerhead#2407]
### What is your Scenario?
Trying to run tests with a runner
 
### What is the Current behavior?
`TypeError: hammerhead.extend is not a function`
 
### What is the Expected behavior?
Tests should run
 
### What is your public web site URL?
N/A

Your website URL (or attach your complete example): 

<details>
<summary>Error: </summary>

 
```js
 TypeError: hammerhead.extend is not a function
    at Object.<anonymous> (D:\Code\MyApp-web\App\node_modules\testcafe-hammerhead\lib\utils\logger.js:31:26)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Module._compile (D:\Code\MyApp-web\App\node_modules\source-map-support\source-map-support.js:547:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (D:\Code\MyApp-web\App\node_modules\testcafe-hammerhead\lib\request-pipeline\context.js:32:38)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Module._compile (D:\Code\MyApp-web\App\node_modules\source-map-support\source-map-support.js:547:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (D:\Code\MyApp-web\App\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:6:39)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Module._compile (D:\Code\MyApp-web\App\node_modules\source-map-support\source-map-support.js:547:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (D:\Code\MyApp-web\App\node_modules\testcafe-hammerhead\lib\proxy\index.js:18:24)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Module._compile (D:\Code\MyApp-web\App\node_modules\source-map-support\source-map-support.js:547:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (D:\Code\MyApp-web\App\node_modules\testcafe-hammerhead\lib\index.js:6:37)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Module._compile (D:\Code\MyApp-web\App\node_modules\source-map-support\source-map-support.js:547:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at lazy (D:\Code\MyApp-web\App\node_modules\import-lazy\index.js:2:51)
    at Object.get (D:\Code\MyApp-web\App\node_modules\import-lazy\index.js:10:11)
    at new TestCafe (D:\Code\MyApp-web\App\node_modules\testcafe\lib\testcafe.js:49:37)
    at Object.construct (D:\Code\MyApp-web\App\node_modules\import-lazy\index.js:19:20)
    at createTestCafe (D:\Code\MyApp-web\App\node_modules\testcafe\lib\index.js:64:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
</details>

<details>
<summary>Your complete app code (or attach your test files):</summary>

```js
const createTestCafe = require('testcafe');

console.log("**********************************"); // logs

let testcafe;
createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        console.log('here'); // errors before his logs
        testcafe = tc;
        const runner = testcafe.createRunner();
        const runOptions = {
            quarantineMode: false,
            startFullscreen: true,
            selectorTimeout: 60000,
            assertionTimeout: 60000,
            pageLoadTimeout: 480000
        }

        return runner
            .src(['e2e/smoke/admin.tests.ts'])
            .browsers(['chrome:headless --no-sandbox'])
            .reporter('teamcity')
            .run(runOptions);
    })
    .then(async failedCount => {
        process.exit();
    })
    .catch(async err => {
        console.log(err);
        process.exit(1);
    })
    .finally(async () => {
        await testcafe.close();
    })

```
</details>

### Steps to Reproduce:

1. Execute `node .\e2e\smoke\smoke-runner.js`
 
### Your Environment details:

* node.js version:                    14.8.0 (also tried 10.19.0)
* browser name and version:  Chrome (latest)
* platform and version:           Windows 10 Professional
* testcafe version:                   1.9.1

**Comment by Ogurecher** [comment]
Hello @djbreen7,
Thank you for your report. Unfortunately, I couldn't reproduce this issue.
At the same time, the cause is likely the missing or incorrectly installed [debug](https://www.npmjs.com/package/debug) module. Try deleting the `node_modules` folder and the `package-lock.json` file, and then run `npm install` to verify the installation.
Let me know if it resolved the issue. If not, please share more information so that I can reproduce the issue and find a solution.

**Comment by djbreen7** [comment]
@Ogurecher I'll give that a shot.
