### ISSUE TITLE
e.toLowerCase is not a function in _shouldOpenInNewWindow

### ISSUE THREAD

**Issue by redbugz** [DevExpress/testcafe-hammerhead#2424]
New to testcafe, didn't see another issue similar

### What is your Scenario?

testcafe, trying to click a button in a form
 
### What is the Current behavior?
  JavaScript error details:
Chrome:
```
      TypeError: e.toLowerCase is not a function
          at Function.t._shouldOpenInNewWindow (http://192.168.1.21:41545/hammerhead.js:5:29205)
          at http://192.168.1.21:41545/hammerhead.js:5:30472
          at http://192.168.1.21:41545/hammerhead.js:7:25103
          at HTMLSpanElement.dispatchEvent (http://192.168.1.21:41545/hammerhead.js:7:18873)
          at e.t._raiseDispatchEvent (http://192.168.1.21:41545/hammerhead.js:8:20771)
          at e.t._dispatchMouseEvent (http://192.168.1.21:41545/hammerhead.js:8:19019)
          at e.t._dispatchMouseRelatedEvents (http://192.168.1.21:41545/hammerhead.js:8:17706)
          at l (http://192.168.1.21:41545/hammerhead.js:8:11948)
          at e.t._simulateEvent (http://192.168.1.21:41545/hammerhead.js:8:12409)
          at e.t.click (http://192.168.1.21:41545/hammerhead.js:8:20860)
```
Firefox:
```
     JavaScript error details:
      e.toLowerCase is not a function
      index.js/S</t._shouldOpenInNewWindow@http://192.168.1.21:33883/hammerhead.js:5:29205
      index.js/S</r._handleFormSubmitting/<@http://192.168.1.21:33883/hammerhead.js:5:30472
      listeners.js/g</r._createEventHandler/<@http://192.168.1.21:33883/hammerhead.js:7:25103
      dispatchEvent@http://192.168.1.21:33883/hammerhead.js:7:18873
      simulator.js/T</t._raiseDispatchEvent@http://192.168.1.21:33883/hammerhead.js:8:20771
      simulator.js/T</t._dispatchMouseEvent@http://192.168.1.21:33883/hammerhead.js:8:19019
      simulator.js/T</t._dispatchMouseRelatedEvents@http://192.168.1.21:33883/hammerhead.js:8:17706
      l@http://192.168.1.21:33883/hammerhead.js:8:11948
      simulator.js/T</t._simulateEvent@http://192.168.1.21:33883/hammerhead.js:8:12409
      simulator.js/T</t.click@http://192.168.1.21:33883/hammerhead.js:8:20860
      va/</Uo.prototype.run@http://192.168.1.21:33883/testcafe-automation.js:1:34635
      va/</tr.prototype._click@http://192.168.1.21:33883/testcafe-automation.js:1:39070
      va/</tr.prototype.run/<@http://192.168.1.21:33883/testcafe-automation.js:1:39533
      a@http://192.168.1.21:33883/hammerhead.js:5:11109
      d@http://192.168.1.21:33883/hammerhead.js:5:11687
      p@http://192.168.1.21:33883/hammerhead.js:5:11723
      n@http://192.168.1.21:33883/hammerhead.js:5:10858
```
 
### What is the Expected behavior?
No errors when clicking a button
 
### What is your public web site URL?
Not currently public, will see if I can create a public reproducible case
<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 await t.click(screen.getByRole('button', { name: /sign in/i }))
// also tried
  await t.click('#login')
```

```html
<button type="submit" name="target" id="login" class="wide-button fs-button fs-button--recommended transitioner">
  <span class="btn-label">Sign In</span>
</button>
```
</details>

<details>
When I set a breakpoint on the e.toLowerCase(). The first time through it is set to "_self", but the 2nd time it's set to the button dom element, which doesn't have the toLowerCase.
I'll keep digging to see if I can tell why or what it is supposed to be instead.
</details>
 
### Your Environment details:

* node.js version:  14.8.0
* browser name and version: Chrome 84 and Firefox 80
* platform and version:          Linux Ubuntu 20.4.1
* other:                                   testcafe 1.9.1, testcafe-hammerhead 17.1.13

**Comment by redbugz** [comment]
Okay, after some debugging, it looks like a poor form structure. Someone gave the submit button the name of "target", which conflicts with the property "target" on the html form element, but now becomes an element instead of a string. So bad form (pun intended) of whomever created this form to use a name that would override a valid property.
I'll close this because i don't think it's reasonable to have to defensively code against someone overriding a valid form property with something completely different. I'll get our team to fix our form.
