### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by david-barak** [DevExpress/testcafe-hammerhead#2452]
Hello, I'm facing an issue similar to the one reported here:  [https://github.com/DevExpress/testcafe-hammerhead/issues/2317](url)
This behavior occurs specifically when I am testing on the cloud deployed version of our application and not the local version. The script that the error happens on seems to be random but it happens every time when I run all of my tests together.

### What is your Scenario?
e2e test using createTestCafe and createRunner
 
### What is the Current behavior?
TestCafe stops working an exception is thrown which can be seen as follows:

![image](https://user-images.githubusercontent.com/27460562/94182992-bfbed100-fe6f-11ea-8a73-1de77b477cbf.png)

### What is the Expected behavior?
TestCafe performs the tests without exception.
 
### What is your public web site URL?
Not available. 

### Your Environment details:

* node.js version: 12.18.4           
* TestCafe version: 1.9.3       
* browser name and version: Google Chrome 85.0.4183.121
* platform and version: Windows 10 Pro 1909

**Comment by miherlosev** [comment]
Hi @david-barak 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a small example so that we can reproduce it on our side?

**Comment by miherlosev** [comment]
Hi @david-barak 
 
Could you please collect request information using the following commands and share it?

```js
set DEBUG=hammerhead:*
testcafe chrome tests 2> hammerhead.log
```

**Comment by david-barak** [comment]
Hi @miherlosev 

This is the information that is stored in the log file using those commands:
![image](https://user-images.githubusercontent.com/27460562/94443772-8dfd8100-0173-11eb-8549-73b773da223a.png)

I've attached the log file as well in case you needed the actual file.

[hammerhead.log](https://github.com/DevExpress/testcafe-hammerhead/files/5293196/hammerhead.log)

**Comment by aleks-pro** [comment]
Hello @david-barak ,

I've run TestCafe against the empty test with commands provided by @miherlosev and have the following output:
```
2020-10-05T07:32:48.321Z hammerhead:proxy Proxy request 79tKEbAyf GET /RQUxaOOgN*1OlqzhdZo/file:///Users/aleks-pro/Work/input-range-selection/index.html {"host":"172.22.1.50:58431","connection":"keep-alive","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","referer":"http://172.22.1.50:58431/browser/idle/a5HPJv8","accept-encoding":"gzip, deflate","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"}
2020-10-05T07:32:48.324Z hammerhead:destination Read file 79tKEbAyf file:///Users/aleks-pro/Work/input-range-selection/index.html
2020-10-05T07:32:48.326Z hammerhead:proxy Proxy resource content info 79tKEbAyf { isPage, charset: iso-8859-1, encoding: undefined, requireProcessing: true }
2020-10-05T07:32:48.348Z hammerhead:proxy Proxy response 79tKEbAyf 200 {"content-type":"text/html","set-cookie":[]}
2020-10-05T07:32:48.467Z hammerhead:service-message Service message {"cmd":"ready","status":{"id":"141.98999999644002","isCommandResult":false,"executionError":null,"pageError":null,"resent":false,"result":null,"consoleMessages":{"1OlqzhdZo":{"log":[],"info":[],"warn":[],"error":[]}},"isPendingWindowSwitching":false,"isFirstRequestAfterWindowSwitching":false},"disableResending":true,"allowRejecting":true,"sessionId":"RQUxaOOgN"}, result {"type":"test-done"}
2020-10-05T07:32:48.516Z hammerhead:service-message Service message {"cmd":"ready","status":{"id":"189.16000000172062","isCommandResult":true,"executionError":null,"pageError":null,"resent":false,"result":null,"consoleMessages":{},"isPendingWindowSwitching":false,"isFirstRequestAfterWindowSwitching":false},"disableResending":true,"allowRejecting":true,"sessionId":"RQUxaOOgN"}, result "test-done-confirmation"
```
Please make sure that the `DEBUG` environment variable has the correct value on your side. You can do it via the `echo %DEBUG%` command.

**Comment by david-barak** [comment]
Hello @aleks-pro ,

Apologies, I run my tests via Git Bash so when I set my environment variable using the provided command it didn't work properly. I've run the tests again and attached the updated hammerhead.log file.

[hammerhead.log](https://github.com/DevExpress/testcafe-hammerhead/files/5328168/hammerhead.log)

**Comment by miherlosev** [comment]
Hi @david-barak 

Thank you for the information. We will research the issue.

**Comment by whschultz** [comment]
I'm getting a similar issue.  I can consistently duplicate it when the web server is up but not responding.  I launch my tests in watch mode, and the first test fails.  

```
Debugger attached.
Prepping...
Starting TestCafe...
The "src", "browsers", and "concurrency" options from the configuration file will be ignored.

Live mode is enabled.
TestCafe now watches source files and reruns   
the tests once the changes are saved.

You can use the following keys in the terminal:
'Ctrl+S' - stops the test run;
'Ctrl+R' - restarts the test run;
'Ctrl+W' - enables/disables watching files;    
'Ctrl+C' - quits live mode and closes the browsers.


Watching the following files:
  <MY_PATH_ON_DISK>\TestCafe\tests\Workflows\1_claims.tests.ts
The "debugOnFail" and "speed" options from the configuration file will be ignored.
 Running tests in:
 - Chrome 89.0.4389.90 / Windows 10

 Claims
  hammerhead:proxy Proxy request TnjgUfK1j GET /OA3LmJdHC/https://localhost:44310/ {"host":"localhost:55646","connection":"keep-alive","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36","sec-fetch-site":"same-origin","sec-fetch-mode":"same-origin","sec-fetch-dest":"empty","referer":"http://localhost:55646/browser/idle/oiXLb9M","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"} +0ms
  hammerhead:destination Destination request TnjgUfK1j GET https://localhost:44310/ {"host":"localhost:44310","connection":"keep-alive","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36","sec-fetch-site":"same-origin","sec-fetch-mode":"same-origin","sec-fetch-dest":"empty","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"} +0ms
  hammerhead:destination Destination response TnjgUfK1j 401 {"cache-control":"private","content-type":"text/html; charset=utf-8","server":"Microsoft-IIS/10.0","www-authenticate":"Negotiate, NTLM","x-powered-by":"ASP.NET","date":"Wed, 31 Mar 2021 18:47:12 GMT","content-length":"5933"} +29ms
  hammerhead:destination Destination request resent with credentials TnjgUfK1j +2ms
  hammerhead:destination Destination request TnjgUfK1j GET https://localhost:44310/ {"host":"localhost:44310","connection":"keep-alive","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36","sec-fetch-site":"same-origin","sec-fetch-mode":"same-origin","sec-fetch-dest":"empty","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","Authorization":"NTLM TlRMTVNTUAABAAAAB7IIogkACQAoAAAAAAAAACgAAAAFASgKAAAAD1RSSUFMQ0FSRA=="} +13ms
  hammerhead:destination:socket Destination request socket first chunk of data TnjgUfK1j 6189 "HTTP/1.1 401 Unauthorized\r\nCache-Control: private\r\nContent-Type: text/html; charset=utf-8\r\nServer: Microsoft-IIS/10.0\r\nWWW-Authenticate: Negotiate\r\nWWW-Authenticate: NTLM\r\nX-Powered-By: ASP.NET\r\nDate: Wed, 31 Mar 2021 18:47:12 GMT\r\nContent-Length: 5933\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\"> \n<html xmlns=\"http://www.w3.org/1999/xhtml\"> \n<head> \n<title>IIS 
10.0 Detailed Error - 401.2 - Unauthorized</title> \n<style type=\"text/css\"> \n<!-- \nbody{margin:0;font-size:.7em;font-family:Verdana,Arial,Helvetica,sans-serif;} \ncode{margin:0;color:#006600;font-size:1.1em;font-weight:bold;} \n.config_source code{font-size:.8em;color:#000000;} \npre{margin:0;font-size:1.4em;word-wrap:break-word;} \nul,ol{margin:10px 0 10px 5px;} \nul.first,ol.first{margin-top:5px;} \nfieldset{padding:0 15px 10px 15px;word-break:break-all;} \n.summary-container fieldset{padding-bottom:5px;margin-top:4px;} \nlegend.no-expand-all{padding:2px 15px 4px 10px;margin:0 0 0 -12px;} \nlegend{color:#333333;;margin:4px 0 8px -12px;_margin-top:0px; \nfont-weight:bold;font-size:1em;} \na:link,a:visited{color:#007EFF;font-weight:bold;} \na:hover{text-decoration:none;} \nh1{font-size:2.4em;margin:0;color:#FFF;} \nh2{font-size:1.7em;margin:0;color:#CC0000;} \nh3{font-size:1.4em;margin:10px 0 0 0;color:#CC0000;} \nh4{font-size:1.2em;margin:10px 0 5px 0; \n}#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:\"trebuchet MS\",Verdana,sans-serif; \n color:#FFF;background-color:#5C87B2; \n}#content{margin:0 0 0 2%;position:relative;} \n.summary-container,.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;} \n.content-container p{margin:0 0 10px 0; \n}#details-left{width:35%;float:left;margin-right:2%; \n}#details-right{width:63%;float:left;overflow:hidden; \n}#server_version{width:96%;_height:1px;min-height:1px;margin:0 0 5px 0;padding:11px 2% 8px 2%;color:#FFFFFF; \n background-color:#5A7FA5;border-bottom:1px solid #C1CFDD;border-top:1px solid #4A6C8E;font-weight:normal; \n font-size:1em;color:#FFF;text-align:right; \n}#server_version p{margin:5px 0;} \ntable{margin:4px 0 4px 0;width:100%;border:none;} \ntd,th{vertical-align:top;padding:3px 0;text-align:left;font-weight:normal;border:none;} \nth{width:30%;text-align:right;padding-right:2%;font-weight:bold;} \nthead th{background-color:#ebebeb;width:25%; \n}#details-right th{width:20%;} \ntable 
tr.alt td,table tr.alt th{} \n.highlight-code{color:#CC0000;font-weight:bold;font-style:italic;} \n.clear{clear:both;} \n.preferred{padding:0 5px 2px 5px;font-weight:normal;background:#006633;color:#FFF;font-size:.8em;} \n--> \n</style> \n \n</head> \n<body> \n<div id=\"content\"> \n<div class=\"content-container\"> \n  <h3>HTTP Error 401.2 - Unauthorized</h3> \n  <h4>You are not authorized to view this page due to invalid authentication headers.</h4> \n</div> \n<div class=\"content-container\"> \n <fieldset><h4>Most likely causes:</h4> \n  <ul> \t<li>No authentication protocol (including anonymous) is selected in IIS.</li> \t<li>Only integrated authentication is enabled, and a client browser was used that does not support integrated authentication.</li> \t<li>Integrated authentication is enabled and the request was sent through a proxy that changed the authentication headers before they reach the Web server.</li> \t<li>The Web server is not configured for anonymous access and a required authorization header was not received.</li> \t<li>The \"configuration/system.webServer/authorization\" configuration section may be explicitly denying the user access.</li> </ul> \n </fieldset> \n</div> \n<div class=\"content-container\"> \n <fieldset><h4>Things you can try:</h4> \n  <ul> \t<li>Verify the authentication setting for the resource and then try requesting the resource using that authentication method.</li> \t<li>Verify that the client browser supports Integrated authentication.</li> \t<li>Verify that the request is not going through a proxy when Integrated authentication is used.</li> \t<li>Verify that the user is not explicitly denied access in the \"configuration/system.webServer/authorization\" configuration section.</li> \t<li>Check the failed request tracing logs for additional information about this error. For more information, click <a href=\"http://go.microsoft.com/fwlink/?LinkID=66439\">here</a>. </li> </ul> \n </fieldset> \n</div> \n \n<div class=\"content-container\"> \n <fieldset><h4>Detailed Error Information:</h4> \n  <div id=\"details-left\"> \n   <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"> \n    <tr class=\"alt\"><th>Module</th><td>&nbsp;&nbsp;&nbsp;IIS Web Core</td></tr> \n    <tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;AuthenticateRequest</td></tr> \n    <tr class=\"alt\"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr> \n 
   <tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x80070005</td></tr> \n     \n   </table> \n  </div> \n  <div id=\"details-right\"> \n   <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"> \n    <tr class=\"alt\"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://localhost:44310/</td></tr> \n    <tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;<MY_SERVER_PATH_ON_DISK></td></tr> \n    <tr class=\"alt\"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr> \n    <tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr> \n     \n   </table> \n   <div class=\"clear\"></div> \n  </div> \n </fieldset> \n</div> \n \n<div class=\"content-container\"> \n <fieldset><h4>More Information:</h4> \n  This error occurs when the WWW-Authenticate header sent to the Web server is not supported by the server configuration. Check the authentication method for the resource, and verify which authentication method the client used. The error occurs when the authentication methods are different. To determine which type of authentication the client is using, check the authentication settings for the client. \n  <p><a href=\"https://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=401,2,0x80070005,19041\">View more information &raquo;</a></p> \n  <p>Microsoft Knowledge Base Articles:</p> \n <ul><li>907273</li><li>253667</li></ul> \n \n </fieldset> \n</div> \n</div> \n</body> \n</html> 
\n" +0ms
  hammerhead:destination:socket Destination request socket first chunk of data TnjgUfK1j 879 "HTTP/1.1 401 Unauthorized\r\nContent-Type: text/html; charset=us-ascii\r\nServer: Microsoft-HTTPAPI/2.0\r\nWWW-Authenticate: NTLM TlRMTVNTUAACAAAAEgASADgAAAAFgomiurjI62C8FZAAAAAAAAAAAL4AvgBKAAAACgBhSgAAAA9UAFIASQBBAEwAQwBBAFIARAACABIAVABSAEkAQQBMAEMAQQBSAEQAAQAcAFQAQwAtADEANgAzADQAMAA3ADkAMgAwADUANwAEABoAdAByAGkAYQBsAGMAYQByAGQALgBjAG8AbQADADgAVABDAC0AMQA2ADMANAAwADcAOQAyADAANQA3AC4AdAByAGkAYQBsAGMAYQByAGQALgBjAG8AbQAFABoAdAByAGkAYQBsAGMAYQByAGQALgBjAG8AbQAHAAgAlyhTQ14m1wEAAAAA\r\nDate: Wed, 31 Mar 2021 18:47:12 GMT\r\nContent-Length: 341\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Not Authorized</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Not Authorized</h2>\r\n<hr><p>HTTP Error 401. The requested resource requires user authentication.</p>\r\n</BODY></HTML>\r\n" +19ms
  hammerhead:destination Destination response TnjgUfK1j 401 {"content-type":"text/html; charset=us-ascii","server":"Microsoft-HTTPAPI/2.0","www-authenticate":"NTLM TlRMTVNTUAACAAAAEgASADgAAAAFgomiurjI62C8FZAAAAAAAAAAAL4AvgBKAAAACgBhSgAAAA9UAFIASQBBAEwAQwBBAFIARAACABIAVABSAEkAQQBMAEMAQQBSAEQAAQAcAFQAQwAtADEANgAzADQAMAA3ADkAMgAwADUANwAEABoAdAByAGkAYQBsAGMAYQByAGQALgBjAG8AbQADADgAVABDAC0AMQA2ADMANAAwADcAOQAyADAANQA3AC4AdAByAGkAYQBsAGMAYQByAGQALgBjAG8AbQAFABoAdAByAGkAYQBsAGMAYQByAGQALgBjAG8AbQAHAAgAlyhTQ14m1wEAAAAA","date":"Wed, 31 Mar 2021 18:47:12 GMT","content-length":"341"} +25ms
  hammerhead:destination Destination request resent with credentials TnjgUfK1j +2ms
  hammerhead:destination Destination request TnjgUfK1j GET https://localhost:44310/ {"host":"localhost:44310","connection":"close","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36","sec-fetch-site":"same-origin","sec-fetch-mode":"same-origin","sec-fetch-dest":"empty","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","Authorization":"NTLM TlRMTVNTUAADAAAAGAAYAHIAAAAYABgAigAAABIAEgBIAAAAGAAYAFoAAAAAAAAAcgAAAAAAAACiAAAABYKIogUBKAoAAAAPVABSAEkAQQBMAEMAQQBSAEQAaABhAG4AawAuAHMAYwBoAHUAbAB0AHoAZUHalLfB8KwAAAAAAAAAAAAAAAAAAAAAPIYcThyQkjVfR9cEEoCftpQiOWH9yQI9"} +27ms
  hammerhead:destination Destination request timeout TnjgUfK1j (25000 ms) +25s
  hammerhead:destination Destination error TnjgUfK1j Error: socket hang up     at connResetException (internal/errors.js:609:14)     at TLSSocket.socketCloseListener (_http_client.js:401:25)     at TLSSocket.emit (events.js:326:22)     at TLSSocket.EventEmitter.emit (domain.js:506:15)     at net.js:675:12     at TCP.done (_tls_wrap.js:568:7)     at TCP.callbackTrampoline (internal/async_hooks.js:126:14) { code: 'ECONNRESET' } +6ms
  hammerhead:proxy Proxy request ZOPtIBZR8 GET /OA3LmJdHC/about:error {"host":"localhost:55646","connection":"keep-alive","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36","sec-fetch-site":"same-origin","sec-fetch-mode":"same-origin","sec-fetch-dest":"empty","referer":"http://localhost:55646/browser/idle/oiXLb9M","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"} +25s
  hammerhead:proxy Proxy resource content info ZOPtIBZR8 { isPage, charset: iso-8859-1, encoding: , requireProcessing: true } +6ms
  hammerhead:proxy Proxy response ZOPtIBZR8 200 {"content-type":"text/html","content-length":"1868","set-cookie":[],"cache-control":"no-cache, no-store, must-revalidate","pragma":"no-cache"} +40ms
  hammerhead:proxy Proxy request zHtyE3yto GET /OA3LmJdHC/about:error {"host":"localhost:55646","connection":"keep-alive","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36","sec-fetch-site":"same-origin","sec-fetch-mode":"same-origin","sec-fetch-dest":"empty","referer":"http://localhost:55646/browser/idle/oiXLb9M","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"} +5ms
  hammerhead:proxy Proxy resource content info zHtyE3yto { isPage, charset: iso-8859-1, encoding: , requireProcessing: true } +3ms
  hammerhead:proxy Proxy response zHtyE3yto 200 {"content-type":"text/html","content-length":"1868","set-cookie":[],"cache-control":"no-cache, no-store, must-revalidate","pragma":"no-cache"} +3ms
  hammerhead:service-message Service message {"cmd":"ready","status":{"id":"25421.189999993658","isCommandResult":false,"executionError":null,"pageError":null,"resent":false,"result":null,"consoleMessages":{"null":{"log":[],"info":[],"warn":[],"error":[]}},"isPendingWindowSwitching":false,"isFirstRequestAfterWindowSwitching":false},"disableResending":true,"allowRejecting":true,"sessionId":"OA3LmJdHC"}, result {"type":"take-screenshot-on-fail","markSeed":null,"markData":""} +0ms
  hammerhead:service-message Service message {"cmd":"ready-for-browser-manipulation","pageDimensions":{"dpr":1.25,"innerWidth":996,"innerHeight":1006,"documentWidth":996,"documentHeight":1006,"bodyWidth":996,"bodyHeight":1006},"disableResending":true,"sessionId":"OA3LmJdHC"}, result {"result":"<MY_PATH_ON_DISK>\\TestCafe\\output\\screenshots\\2021-03-31_14-47-11\\test-1\\Chrome_89.0.4389.90_Windows_10\\run-1errors\\1.png","error":null} +3s
  hammerhead:service-message Service message {"cmd":"ready","status":{"id":"28288.185000012163","isCommandResult":true,"executionError":null,"pageError":null,"resent":false,"result":"<MY_PATH_ON_DISK>\\TestCafe\\output\\screenshots\\2021-03-31_14-47-11\\test-1\\Chrome_89.0.4389.90_Windows_10\\run-1errors\\1.png","consoleMessages":{},"isPendingWindowSwitching":false,"isFirstRequestAfterWindowSwitching":false},"disableResending":true,"allowRejecting":true,"sessionId":"OA3LmJdHC"}, result {"type":"set-breakpoint","isTestError":true} +336ms

----
Chrome 89.0.4389.90 / Windows 10
DEBUGGER PAUSE ON FAILED TEST:
- Error in fixture.beforeEach hook -
A request to "https://localhost:44310/" has failed.
Use quarantine mode to perform additional attempts to execute this test.
You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

Error details:
Failed to complete a request to "https://localhost:44310/" within the timeout period. The problem may be related to local machine's network or firewall settings, server outage, or network problems that make the server inaccessible.

Browser: Chrome 89.0.4389.90 / Windows 10
Screenshot: <MY_PATH_ON_DISK>\TestCafe\output\screenshots\2021-03-31_14-47-11\test-1\Chrome_89.0.4389.90_Windows_10\run-1errors\1.png

53 |        return join([Fixture.baseUrl, trimStart(subpath, "/")], "/");
54 |    }
55 |
56 |    public async beforeEach(t: TestController) {
57 |        // await PageBase.waitLoadingComplete();
> 58 |        await t.maximizeWindow();
59 |        await PageBase.waitLoadingComplete();
60 |    }
61 |
62 |    public async afterEach(t: TestController) {
63 |        const consoleMessages = await t.getBrowserConsoleMessages();

at Fixture.<anonymous> (<MY_PATH_ON_DISK>\TestCafe\common\FixtureFactory.ts:58:17)
at <anonymous> (<MY_PATH_ON_DISK>\TestCafe\node_modules\tslib\tslib.js:117:75)
at Object.__awaiter (<MY_PATH_ON_DISK>\TestCafe\node_modules\tslib\tslib.js:113:16)
at Fixture.beforeEach (<MY_PATH_ON_DISK>\TestCafe\common\FixtureFactory.ts:43:24)
at <anonymous> (<MY_PATH_ON_DISK>\TestCafe\tests\Workflows\1_claims.tests.ts:51:13)
at <anonymous> (<MY_PATH_ON_DISK>\TestCafe\node_modules\tslib\tslib.js:117:75)
at Object.__awaiter (<MY_PATH_ON_DISK>\TestCafe\node_modules\tslib\tslib.js:113:16)
at <anonymous> (<MY_PATH_ON_DISK>\TestCafe\tests\Workflows\1_claims.tests.ts:48:32)
----
```

At this point, it has taken me to http://localhost:57535/yHxTlMey2/about:error
Then about 90 seconds later, I get the following:

```
  hammerhead:destination Destination error TnjgUfK1j Error: read ECONNRESET     at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)     at TLSWrap.callbackTrampoline (internal/async_hooks.js:126:14) { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } +2m
Waiting for the debugger to disconnect...
<MY_PATH_ON_DISK>\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\connection-reset-guard.js:20
  throw err;
  ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at RequestPipelineContext.redirect (<MY_PATH_ON_DISK>\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\context.js:311:9)
    at LiveModeTestRun.handlePageError (<MY_PATH_ON_DISK>\TestCafe\node_modules\testcafe\src\test-run\index.js:305:13)
    at SessionController.handlePageError (<MY_PATH_ON_DISK>\TestCafe\node_modules\testcafe\src\test-run\session-controller.js:43:36)
    at error (<MY_PATH_ON_DISK>\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\utils.js:114:48)
    at DestinationRequest.<anonymous> (<MY_PATH_ON_DISK>\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\utils.js:84:9)
    at DestinationRequest.emit (events.js:314:20)
    at DestinationRequest.EventEmitter.emit (domain.js:483:12)
    at DestinationRequest._onError (<MY_PATH_ON_DISK>\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:201:17)
    at ClientRequest.<anonymous> (<MY_PATH_ON_DISK>\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:83:38) { 
  code: 'ERR_HTTP_HEADERS_SENT',
  domainThrown: true
}
```

Then the process dies.

According to my package-lock.json I'm running:
testcafe: 1.12.0
testcafe-hammerhead: 19.4.1

Since I see there are newer versions, I just updated to the following:
testcafe: 1.13.0
testcafe-hammerhead: 19.5.0

Got the same error with different line numbers:

```
  hammerhead:destination Destination error 4Z5DwrT8J Error: read ECONNRESET     at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)     at TLSWrap.callbackTrampoline (internal/async_hooks.js:126:14) { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } +2m
Waiting for the debugger to disconnect...
C:\Users\hank.schultz\source\repos\QuickPath\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\connection-reset-guard.js:16
    throw err;
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at RequestPipelineContext.redirect (C:\Users\hank.schultz\source\repos\QuickPath\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\context.js:250:13)
    at LiveModeTestRun.handlePageError (C:\Users\hank.schultz\source\repos\QuickPath\TestCafe\node_modules\testcafe\src\test-run\index.js:312:13)
    at SessionController.handlePageError (C:\Users\hank.schultz\source\repos\QuickPath\TestCafe\node_modules\testcafe\src\test-run\session-controller.js:43:36)
    at error (C:\Users\hank.schultz\source\repos\QuickPath\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\utils.js:87:21)
    at DestinationRequest.<anonymous> (C:\Users\hank.schultz\source\repos\QuickPath\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\utils.js:58:17)
    at DestinationRequest.emit (events.js:314:20)
    at DestinationRequest.EventEmitter.emit (domain.js:483:12)
    at DestinationRequest._onError (C:\Users\hank.schultz\source\repos\QuickPath\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:170:18)
    at ClientRequest.<anonymous> (C:\Users\hank.schultz\source\repos\QuickPath\TestCafe\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:59:44) { 
  code: 'ERR_HTTP_HEADERS_SENT',
  domainThrown: true
}
```

**Comment by andrzej-kodify** [comment]
As a silly workaround I've used https://www.npmjs.com/package/patch-package and created such patch

```
diff --git a/node_modules/testcafe-hammerhead/lib/request-pipeline/context.js b/node_modules/testcafe-hammerhead/lib/request-pipeline/context.js
index 8127266..26e11fc 100644
--- a/node_modules/testcafe-hammerhead/lib/request-pipeline/context.js
+++ b/node_modules/testcafe-hammerhead/lib/request-pipeline/context.js
@@ -301,8 +301,12 @@ class RequestPipelineContext {
   redirect(url) {
     if (this.isWebSocket) throw new Error(CANNOT_BE_USED_WITH_WEB_SOCKET_ERR_MSG);
     const res = this.res;
-    res.statusCode = 302;
-    res.setHeader(_builtinHeaderNames.default.location, url);
+    try {
+      res.statusCode = 302;
+      res.setHeader(_builtinHeaderNames.default.location, url);
+    } catch (error) {
+      console.error('All your base are belong to us', error);
+    }
     res.end();
   }
 
```
Haven't noticed any side effects so far
