### ISSUE TITLE
Unable to run hammerhead playground on node version 12

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe-hammerhead#2457]
### Steps to Reproduce:

I followed [these](https://github.com/DevExpress/testcafe-hammerhead#first-look) steps to run the Hammerhead playground and the error occurred:
`ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/Users/aleks-pro/Work/testcafe-hammerhead/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/aleks-pro/Work/testcafe-hammerhead/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/aleks-pro/Work/testcafe-hammerhead/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)`

It looks like the problem related to this issue https://github.com/gulpjs/gulp/issues/2324
 
### Your Environment details:

* node.js version:                    v12.18.0 
* platform and version:          macOS 10.15

**Comment by miherlosev** [comment]
At present, the `gulp#4.x` is used.
