### ISSUE TITLE
Error in Hammerhead.js - New Contacts in Salesforce Lighting Experience '22

### ISSUE THREAD

**Issue by AndrewYoungQA** [DevExpress/testcafe-hammerhead#2773]
### What is your Scenario?

Issue: When User logs into Salesforce, selects new Contact button, they are met with the following hammerhead.js error.

`Uncaught Error in $A.getCallback() [Maximum call stack size exceeded]
throws at http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:90:31. Caused by: Error in $A.getCallback() [Maximum call stack size exceeded]
{anonymous}()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:25015
eval()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
lt.passthruSetTrap [as set]()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
PropertyAccessorsInstrumentation._propertySetter()@hammerhead.js:20915:33`

### What is the Current behavior?

After selecting Contacts tab, or New Contact Button, the following error message is being returned.

`Uncaught Error in $A.getCallback() [Maximum call stack size exceeded]
throws at http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:90:31. Caused by: Error in $A.getCallback() [Maximum call stack size exceeded]
{anonymous}()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:25015
eval()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
lt.passthruSetTrap [as set]()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
PropertyAccessorsInstrumentation._propertySetter()@hammerhead.js:20915:33`

### What is the Expected behavior?

After Selecting the Contact tab, or new Contact button, the user should be presented with a contact modal that allows users to input contact data.

### What is your public website URL? (or attach your complete example)

For our website there is no public URL, however you will be able to reproduce the error using the Trailhead Lightning Demo Site.
https://trailblazer.me/trailblazerlogin
https://resilient-shark-wlmrgy-dev-ed.lightning.force.com/lightning/o/Contact/list?filterName=Recent

### What is your TestCafe test code?

This is being recreated using the testcafe-hammerhead project and is reproducible through selections in the Trailhead site.

### Steps to Reproduce

1. Setup free Trailhead User at: https://trailblazer.me/trailblazerlogin , using email.
2. Installed the 'testcafe-hammerhead' project
3. Run Command Line : node node_modules/gulp/bin/gulp http-playground
4. In the field on the localhost:1400 page, we enter: https://trailhead.salesforce.com/en/content/learn/modules/accounts_contacts_lightning_experience/accounts-and-contacts-lightning
5. Select 'Proxy!' button
6. Select 'Log In' on salesforce / trailhead site.
7. Select 'Email' icon
8. Enter Email for account set up in 'Step 1'
9. Select 'Log in' Button.
10. Retrieve your Single use code from email sent to email address used in 'Step 1 / Step 8'
11. Select 'Continue' Button
12. Select 'Skip for Now' link
13. Confirm Page: https://trailhead.salesforce.com/en/content/learn/modules/accounts_contacts_lightning_experience/accounts-and-contacts-lightning loads successfully
14. Scroll to the bottom of the page and select the 'Launch' Button (note. On the initial run this step took a while for the launch button to become active, it eventually did however and was able to proceed)
15. Wait for Salesforce Lightning Env to load: https://resilient-shark-wlmrgy-dev-ed.lightning.force.com/lightning/page/home
16. *At this point you may hit the error. If not { Select the dot grid in the top left, then select 'Sales' from the ddl. If Sales is not visible search 'Sales' in the 'Search apps and items...' field.
![image](https://user-images.githubusercontent.com/40370410/174357206-7dff73e2-b906-460f-8e0e-90f041c45c02.png)
17. Once Sales Dashboard is loaded Select the 'Contacts' tab.
18. *At this point you will see the error message, if not select 'New' Contact button.
![image](https://user-images.githubusercontent.com/40370410/174357462-b252683d-b323-43c8-a64a-5fefa13558d3.png)
`Uncaught Error in $A.getCallback() [Maximum call stack size exceeded]
throws at http://localhost:1401/fQA1lRrUK!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:90:31. Caused by: Error in $A.getCallback() [Maximum call stack size exceeded]
{anonymous}()@http://localhost:1401/fQA1lRrUK!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:25015
eval()@http://localhost:1401/fQA1lRrUK!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
lt.passthruSetTrap [as set]()@http://localhost:1401/fQA1lRrUK!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
PropertyAccessorsInstrumentation._propertySetter()@hammerhead.js:20915:33`

### TestCafe version

1.19.0

### Node.js version

v16.15.1

### Command-line arguments

node node_modules/gulp/bin/gulp http-playground

### Browser name(s) and version(s)

Version 102.0.5005.115 (Official Build) (64-bit)

**Comment by aozomaro** [comment]
+1 I have been experiencing the same issue since last weekend (the sfdc release)

**Comment by Aleksey28** [comment]
Thank you for the example. I reproduced the issue. We will update this thread once we have any news. Let us know if you have additional information about the issue.

**Comment by AndrewYoungQA** [comment]
Thank you @Aleksey28 
Looking forward to progress on this matter.

**Comment by AndrewYoungQA** [comment]
![image](https://user-images.githubusercontent.com/40370410/179555208-5902d341-fe48-4559-b756-b97354dfe2dd.png)

We are seeing continued failure with this issue, is there any soft ETA or update available that we can relay to the team?
I apologize @Aleksey28 , I am not trying to put any pressure on the situation but we have been down for a while as a result of this issue and need to communicate an expectation back to those in charge.
