### ISSUE TITLE
Script error for http://digg.com/

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#665]
see https://testcafe-hhhm.devexpress.com/history?timestamp=1467918418380&siteUrl=http://www.wp.pl/

Stack trace:
```javascript
"Error: Blocked a frame with origin "http://localhost:1401" from accessing a cross-origin frame.
    at Error (native)
    at Object.findByName (http://localhost:1401/hammerhead.js:9641:33)
    at ElementSandbox._overridedSetAttributeCore (http://localhost:1401/hammerhead.js:7097:83)
    at HTMLFormElement.setAttribute (http://localhost:1401/hammerhead.js:7266:39)
    at Object.set (http://localhost:1401/hammerhead.js:2202:39)
    at value (http://localhost:1401/hammerhead.js:2471:183)
    at u (http://localhost:1401/r1ahQ1TU!s!utf-8/http://platform.twitter.com/widgets.js:10:3490)
    at http://localhost:1401/r1ahQ1TU!s!utf-8/http://platform.twitter.com/widgets.js:10:2455"
```

**Comment by miherlosev** [comment]
Reproduced not stable.

**Comment by miherlosev** [comment]
Dublicate of https://github.com/DevExpress/testcafe-hammerhead/issues/669
