### ISSUE TITLE
Browsers get stuck while searching on 'http://yahoo.com'

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe-hammerhead#866]
It's reproducing in all browsers in hammerhead-playground
http://screencast.com/t/5ROkcM3Fety

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Unhandled error inside `processScript`.

Script for reproduce:
```js
var b = {};
b.onerror = b.onload = function (a) {
    location = a;
};
```

Call stack:
```js
TypeError: ExprGen[$expr.type] is not a function
    at exprToJs (C:\Hammerhead_github\lib\processing\script\tools\esotope.js:2005:24)
    at Object.generateExpressionStatement [as ExpressionStatement] (C:\Hammerhead_github\lib\processing\script\tools\esotope.js:1657:22)
    at Object.generateBlockStatement [as BlockStatement] (C:\Hammerhead_github\lib\processing\script\tools\esotope.js:1490:32)
    at generateFunctionBody (C:\Hammerhead_github\lib\processing\script\tools\esotope.js:643:28)
    at Object.generateFunctionExpression [as FunctionExpression] (C:\Hammerhead_github\lib\processing\script\tools\esotope.js:1205:9)
    at Object.generateCallExpression [as CallExpression] (C:\Hammerhead_github\lib\processing\script\tools\esotope.js:1058:31)
    at Object.generateCallExpression [as CallExpression] (C:\Hammerhead_github\lib\processing\script\tools\esotope.js:1058:31)
    at run (C:\Hammerhead_github\lib\processing\script\tools\esotope.js:2028:92)
    at generate (C:\Hammerhead_github\lib\processing\script\tools\esotope.js:2114:12)
    at getCode (C:\Hammerhead_github\lib\processing\script\index.js:89:38)
```

**Comment by mathieudutour** [comment]
Any idea about when this fix will get published?

**Comment by AlexanderMoskovkin** [comment]
The fix will be included in the next TestCafe version (0.12.0), we plan to publish it in the next one-two weeks. But we can publish a `daily-build` version with the fix today.

**Comment by mathieudutour** [comment]
That'd be awesome 👍

**Comment by AlexanderMoskovkin** [comment]
Ok, will do it soon, I'll notify you

**Comment by churkin** [comment]
@mathieudutour I have published new testcafe release https://github.com/DevExpress/testcafe/releases/tag/v0.12.0-alpha3 that contains this fix.

**Comment by churkin** [comment]
@mathieudutour I have published new testcafe release https://github.com/DevExpress/testcafe/releases/tag/v0.12.0-alpha4 that contains this fix.
