### ISSUE TITLE
Search on mail.ru hungs under proxing

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#906]
see [video](http://screencast.com/t/L6BmIB9usj3)

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
Unhandled error inside processScript.

Script for reproduce:
```javascript
new function(a){location=a.attr("href"),a.click()}
```

Call stack:
```
ExprGen[$child.type] is not a function

TypeError: ExprGen[$child.type] is not a function
    at Object.generateSequenceExpression [as SequenceExpression] (d:\Projects\testcafe-hammerhead\lib\processing\script\tools\esotope.js:986:33)
    at exprToJs (d:\Projects\testcafe-hammerhead\lib\processing\script\tools\esotope.js:2005:24)
    at Object.generateExpressionStatement [as ExpressionStatement] (d:\Projects\testcafe-hammerhead\lib\processing\script\tools\esotope.js:1657:22)
    at Object.generateBlockStatement [as BlockStatement] (d:\Projects\testcafe-hammerhead\lib\processing\script\tools\esotope.js:1490:32)
    at generateFunctionBody (d:\Projects\testcafe-hammerhead\lib\processing\script\tools\esotope.js:643:28)
    at Object.generateFunctionExpression [as FunctionExpression] (d:\Projects\testcafe-hammerhead\lib\processing\script\tools\esotope.js:1205:9)
    at Object.generateCallExpression [as CallExpression] (d:\Projects\testcafe-hammerhead\lib\processing\script\tools\esotope.js:1058:31)
    at exprToJs (d:\Projects\testcafe-hammerhead\lib\processing\script\tools\esotope.js:2005:24)
    at Object.generateExpressionStatement [as ExpressionStatement] (d:\Projects\testcafe-hammerhead\lib\processing\script\tools\esotope.js:1657:22)
    at Object.generateBlockStatement [as BlockStatement] (d:\Projects\testcafe-hammerhead\lib\processing\script\tools\esotope.js:1490:32)
```

**Comment by miherlosev** [comment]
It is dublicate of #866
