### ISSUE TITLE
A lot of errors during login/logout on http://mail.ru

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#907]
see [video](http://screencast.com/t/EvAiC1DY)

After login, hammerhead fails with server error:
```js
Error: Cant set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.res.setHeader (C:\Hammerhead_github\node_modules\connect\lib\patch.js:59:22)
    at RequestPipelineContext.closeWithError (C:\Hammerhead_github\lib\request-pipeline\context.js:256:22)
    at error (C:\Hammerhead_github\lib\request-pipeline\index.js:259:85)
    at DestinationRequest.<anonymous> (C:\Hammerhead_github\lib\request-pipeline\index.js:95:24)
    at emitOne (events.js:96:13)
    at DestinationRequest.emit (events.js:188:7)
    at DestinationRequest._onTimeout (C:\Hammerhead_github\lib\request-pipeline\destination-request\index.js:176:18)
    at ClientRequest.<anonymous> (C:\Hammerhead_github\lib\request-pipeline\destination-request\index.js:106:31)
    at ClientRequest.g (events.js:291:16)
```

**Comment by miherlosev** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by miherlosev** [comment]
For health monitor we have a simular errors starts from 2016-11-09 22:00:05 build
