### ISSUE TITLE
Server shutdown with "Error: Can't set headers after they are sent."

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#937]
Reproducing on https://e.mail.ru/messages/inbox/
The `fatalError` event emits two times.
First stack:
```
    at RequestPipelineContext.closeWithError (d:\Projects\testcafe-hammerhead\lib\request-pipeline\context.js:268:44)
    at error (d:\Projects\testcafe-hammerhead\lib\request-pipeline\index.js:264:85)
    at DestinationRequest.<anonymous> (d:\Projects\testcafe-hammerhead\lib\request-pipeline\index.js:95:24)
    at emitOne (events.js:77:13)
    at DestinationRequest.emit (events.js:169:7)
    at DestinationRequest._onError (d:\Projects\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:184:46)
    at ClientRequest.<anonymous> (d:\Projects\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:103:31)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketCloseListener (_http_client.js:235:9)
```
Second stack:
```
    at RequestPipelineContext.closeWithError (d:\Projects\testcafe-hammerhead\lib\request-pipeline\context.js:268:44)
    at error (d:\Projects\testcafe-hammerhead\lib\request-pipeline\index.js:264:85)
    at DestinationRequest.<anonymous> (d:\Projects\testcafe-hammerhead\lib\request-pipeline\index.js:95:24)
    at emitOne (events.js:77:13)
    at DestinationRequest.emit (events.js:169:7)
    at DestinationRequest._onTimeout (d:\Projects\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:176:18)
    at ClientRequest.<anonymous> (d:\Projects\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:106:31)
    at ClientRequest.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at ClientRequest.emit (events.js:166:7)
```

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by inikulin** [comment]
@LavrovArtem Node throws this error when you try to modify response headers once you already started sending the body

**Comment by LavrovArtem** [comment]
@inikulin I know
